// ***********************************************
// This example commands.ts shows you how to
// create various custom commands and overwrite
// existing commands.
//
// For more comprehensive examples of custom
// commands please read more here:
// https://on.cypress.io/custom-commands
// ***********************************************
//
//
// -- This is a parent command --
// Cypress.Commands.add('login', (email, password) => { ... })
//
//
// -- This is a child command --
// Cypress.Commands.add('drag', { prevSubject: 'element'}, (subject, options) => { ... })
//
//
// -- This is a dual command --
// Cypress.Commands.add('dismiss', { prevSubject: 'optional'}, (subject, options) => { ... })
//
//
// -- This will overwrite an existing command --
// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })

Cypress.Commands.add("typeLogin", (username, password) => {
  cy.visit("/");
  cy.get('[data-cy="email"]').type(username);
  cy.get('[data-cy="senha"]').type(password);
  cy.get('[data-cy="loginButton"]').click(); //Botão Acessar da página principal
});

// Generated by Cypress Author on 2026-05-30.
// Logs in via cy.session() so Cypress caches and restores the authenticated
// state (cookies, localStorage, sessionStorage) between tests, avoiding a full
// UI login on every beforeEach.
Cypress.Commands.add("loginSession", (email, password) => {
  cy.session(
    [email, password],
    () => {
      cy.visit("/");
      cy.get('[data-cy="email"]').type(email);
      cy.get('[data-cy="senha"]').type(password);
      cy.get('[data-cy="loginButton"]').click();
      // Wait for the authenticated state before Cypress snapshots the session
      cy.get('[data-cy="user-menu"]').should("be.visible");
    }
  );
});
