/**
 * Helper generated by Cypress Author on 2026-05-30.
 * Reusable functions to handle state and navigation for proposal submission.
 */

export function irAteInfosComplementares() {
  // Use cached session to bypass UI login steps if already logged in
  cy.loginSession("gabriel.fernandes.12@sig.com", "@Dev12345");

  // Intercept and mock proposal creation to avoid polluting the database
  cy.intercept("POST", "**/api/proposta", {
    statusCode: 201,
    body: { id: 9999 }
  }).as("savePropostaMock");

  // Intercept and mock proposal updates (PUT) to prevent 404 on mock ID 9999
  cy.intercept("PUT", "**/api/proposta/9999", {
    statusCode: 200,
    body: { id: 9999 }
  }).as("updatePropostaMock");

  // Intercept and mock proposal details fetching (GET)
  cy.intercept("GET", "**/api/proposta/9999", {
    statusCode: 200,
    body: { id: 9999, titulo: "Teste de submissão de proposta" }
  }).as("getPropostaMock");


  cy.visit("/");
  
  // Navigate to proposal creation
  cy.get(".css-18juej0.ekicsf50").first().click();
  cy.contains("Edital 2026-0001 Sig Cypress")
    .closest(".e1mpo2wc53")
    .find("button")
    .first()
    .click({ force: true });
  cy.get('[data-cy="criar-proposta"]').click();

  // Populate first step (Infos Iniciais) using the fixture
  cy.fixture("submeter-proposta/infos-iniciais/infos-iniciais").then((dados) => {
    // Append a random number to the title to ensure uniqueness on every run
    const uniqueTitle = `${dados.titulo} ${Math.floor(Math.random() * 100000)}`;
    
    cy.get('[data-cy="titulo"]').type(uniqueTitle);
    cy.get('[data-cy="search-tipo-evento-id"]').click();
    cy.contains(dados.tipo_evento).click();
    cy.get('[data-cy="search-estado-execucao-evento"]').click();
    cy.contains(dados.estado_execucao).click();
    cy.get('[data-cy="search-municipio-execucao-evento"]').click();
    cy.contains(dados.municipio_execucao).click();
    
    // Proceed to Step 2 (Infos Complementares)
    cy.get('[data-cy="next-button"]').click();
    cy.wait("@savePropostaMock");
  });
}

export function irAteDadosPessoais() {
  irAteInfosComplementares();

  cy.contains("MEI").parent().find("input[type='radio']").click({ force: true });
  //cy.fixture("submeter-proposta/infos-complementares/infos-complementares").then((dados) => {
   // cy.get("[data-cy='formularioPropostaInformacaoComplementar.pergunta-200']").type(dados.descricao);
  //});

  cy.get('[data-cy="next-button"]').click();
  cy.get('[data-cy="next-button"]').click();
  cy.wait("@updatePropostaMock");
}